### ISSUE TITLE
Pairing with newer Hue Hub firmware fails

### ISSUE THREAD

**Issue by mrstegeman** [mozilla-iot/homekit-adapter#12]
The hub advertises itself as `pv=1.1`, rather than `pv=1.0`. They should be compatible, but...? PairSetup is failing on M4, with error set to `kTLVError_Unknown`.

**Comment by freaktechnik** [comment]
The error is also returned for M2, as a response to M3.

This v1.1 protocol is compatible with iOS 10, so it must either have been in planning for a longer time or the homekit protocol implementation here has some flaw.

**Comment by mrstegeman** [comment]
I'm guessing the latter. According to the spec, if the major version is the same, then it should still be compatible.

**Comment by mrstegeman** [comment]
There is a new version of the spec out now, which corresponds to `pv=1.1`, but the existing pairing protocol should work just fine. There is a new pairing protocol, but it should be dictated by the controller, i.e. this adapter.
