### ISSUE TITLE
Where can I find the pin I need to submit?

### ISSUE THREAD

**Issue by sjaccoo** [mozilla-iot/homekit-adapter#23]
I have done some searching but I can't find anything on the internet. I'm also new to this so sorry if its a dumb question... But where can I find the pin? I've been trying to add my hue lights, 2 smart sockets from aliexpress and an LED strip

**Comment by mrstegeman** [comment]
Most HomeKit devices should either have the PIN on the product itself, or inside the packaging. Alternatively, there may be a QR code in the shape of a house.

The PIN is of the form 123-45-678
