### ISSUE TITLE
Updating the docs

### ISSUE THREAD

**Issue by ntwb** [mozilla-iot/homekit-adapter#26]
After #22 I think the docs need further updating.

Looking at https://github.com/mozilla-iot/homekit-adapter/blob/master/README.md#configuration it references:

> Click on the _Configure_ button for the HomeKit add-on.

If I'm not mistaken this was removed in #22?

Edit: I think the entire configuration section requires updating now as there is "nothing" to configure

Edit2: I've no idea how to "connect" the _gateway_ with my iPad Home/HomeKit app, adding docs for this would also be appreciated

**Comment by mrstegeman** [comment]
Correct, there's no longer anything to configure.

As for connecting with the Home app, that's currently not possible due to technical limitations. From the README:

> **NOTE**: Devices typically need to be unpaired from Android/iOS before using them with the gateway.
