### ISSUE TITLE
Eve Window / Door Sensors pairing is not working

### ISSUE THREAD

**Issue by plackettsj1** [mozilla-iot/homekit-adapter#43]
I have multiple gateways and multiple Eve Window / Door Sensors - there is now an issue with pairing new devices. Everything appears to be working for previously paired devices.

The summary is
1) With a fresh install I am able to install 1 device only to the gateway provided that it was not powered up (aka battery was removed) when the gateway was started. However even this is temporary. After either rebooting the gateway or the rpi the device is never again recognised and remains as a "Custom Thing". From my logs it may be a race condition in that the device is seen in the logs before the Homekit adapter is loaded.

2) I am unable to pair any device on a gateway that already has existing devices paired on it. I get a generic  timeout error and no more information. The Web interface reports pin incorrect (although this is not consistent with the logs). As I have had the gateways for a while, the devices were paired with previous versions of the software (v5 of Homekit I think)

Detail:
I have tried the following combinations, all with the latest software Gateway 0.9.2 and Homekit 0.7.1. 
1) Stretch with on-board bluetooth (LAN only and Wifi only)
2) Stretch with USB bluetooth (LAN only and Wifi only)
3) Buster with on-board bluetooth on RPI 3 (LAN only and Wifi only)
4) Buster with USB bluetooth on RPI3 (LAN only and Wifi only)
5) Buster with on-board Bluetooth on RPI4 (LAN only and Wifi only)
6) Buster with USB Bluetooth on RPI4 (LAN only and Wifi only)

All of the combinations result in the same outcomes - so I don't think its to do with the hardware. I have also move the sensors close to the rpi's and had them further away - again this makes no difference to the outcome.

I am attaching two logs 
- one is from the fresh install of Things Gateway - where you can see the first device pair and then subsequent devices do not pair
-the second is from an existing gateway with multiple devices previously paired - you can see the pairing failure and that devices are found before the homekit adapter has loaded. I am not sure this is releveant - but it might be :-)

Thanks for looking at this :-)

Simon
[run-app.log.2019-10-18-gateway5-existing_devices_added.txt](https://github.com/mozilla-iot/homekit-adapter/files/3766959/run-app.log.2019-10-18-gateway5-existing_devices_added.txt)
[run-app.log.2019-10-18-was_a_fresh_install.txt](https://github.com/mozilla-iot/homekit-adapter/files/3766960/run-app.log.2019-10-18-was_a_fresh_install.txt)

**Comment by plackettsj1** [comment]
PS - If there is anything I can do to help with testing - please let me know - I have multiple rpi's and sensors so can try things out if that would help 
Simon

**Comment by plackettsj1** [comment]
I have made this work - I have now disabled both the onboard bluetooth and the onboard wifi by editing /boot/config.txt and adding in the [all] section
dtoverlay=pi3-disable-bt
dtoverlay=disable-wifi
(Note: these worked for both RPI3B+ and RPI4)

I have a USB bluetooth device plugged in to provide the connection. 

To pair a new EVE Sensor
1) Ensure the EVE Sensor is reset (press the reset until the EVE sensor flashes five times)
2) Wait for the EVE Sensor to restart - single red flash
3) Take out the battery from the sensor
4) sudo systemctl stop mozilla-iot-gateway
5) sudo systemctl stop bluetooth
6) sudo systemctl restart bluetooth
7) sudo systemctl restart mozilla-iot-gateway
8) Go to the web interface and press the + for new devices
9) If any devices are found cancel them all until all that is left is Scanning for New Devices
10) Put the battery back into the Eve Sensor
11) Device will appear and should be the only 1 on the list
12) Add the password in either format (all 8 digits or xxx-xx-xxx)
13) Device pairs every time

**Comment by mrstegeman** [comment]
Wow! Thank you for all of your experimentation. I'd imagine some of the interim steps could be removed. However, I'm curious to see if you'll end up running into regular "disconnected" issues after several days. Would you mind updating this issue in a few days and let me know?

For reference, with the built-in Bluetooth adapter, I start seeing lots of timeouts and disconnected errors in my log after several days (time varies depending on number of devices connected). At that point, the only way to resolve the issue is to do a `systemctl restart bluetooth` or restart the RPi all together.

**Comment by plackettsj1** [comment]
Hi Michael - I get the disconnects very quickly - varies from a few minutes to a few 10s of mins - I have a log trawler that spots them and restarts the gateway and bluetooth - its not elegant but it keeps the sensors alive. The EVE sensors seem to be very picky!!
Simon

**Comment by mrstegeman** [comment]
Unfortunately, it's not just the Eve sensors. I've had the same thing happen with other Bluetooth devices. There seem to be some issues with [noble](https://github.com/abandonware/noble) (as discussed [here](https://github.com/mozilla-iot/homekit-adapter/issues/30)). I've been watching a new project called [sblendid](https://github.com/abandonware/noble) which I hope can replace noble and resolve some of these issues.

**Comment by plackettsj1** [comment]
Hi - I am capturing frequency of restarts based on the Disconnected message - so happy to test if and when sblendid becomes an option - as I have a baseline failure rate!
